### ISSUE TITLE
[BUG] Level 3 Green Check Marks Early

### ISSUE THREAD

**Issue by rajbsrivastava** [Accessible-Technology-in-Sign/PopSign#2] opened 2021-02-01 17:08 UTC
**Describe the bug**
Green check marks define when you complete a level. However, level 3 gives them too early in an unintended spot.

**To Reproduce**
Simply play through Level 3 as normal and this may pop up.

**Expected behavior**
Green check marks should only appear at the top row of bubbles.

**Screenshots**
![PopSign Level 3 Green Checks Bug 1](https://user-images.githubusercontent.com/39221322/106492658-2e4b1580-6486-11eb-8939-7d8531b0feed.png)
![PopSign Level 3 Green Checks Bug 2](https://user-images.githubusercontent.com/39221322/106492676-31460600-6486-11eb-8cc1-fcf1b4d6e9bc.png)

**Smartphone (please complete the following information):**
 - Done on proper version of Unity

**Comment by pamplemoussecache** [comment] 2021-02-01 21:35
Duplicate of issue #3 , closing

**Closed by pamplemoussecache** 2021-02-01 21:35 UTC
Labels: bug
